name: PR Checks

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    if: '!github.event.pull_request.draft'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Check code formatting
        run: npm run format --check
        continue-on-error: false

      - name: Lint code
        run: npm run lint
        continue-on-error: false

      - name: Build project
        run: npm run build
        continue-on-error: false

      - name: Run unit tests
        run: npm run test:unit
        continue-on-error: false

      - name: Run integration tests
        run: npm run test:integration
        continue-on-error: false

      - name: Check test coverage threshold
        run: npm test -- --coverage --coverageThreshold='{"global":{"statements":90,"branches":85,"functions":90,"lines":90}}'
        continue-on-error: false

  pr-ready:
    name: PR Ready for Review
    needs: quality-gate
    runs-on: ubuntu-latest
    if: success()
    
    steps:
      - name: PR Quality Check Passed
        run: |
          echo "✅ All quality checks passed!"
          echo "✅ Code formatting: PASSED"
          echo "✅ Linting: PASSED" 
          echo "✅ Build: PASSED"
          echo "✅ Unit tests: PASSED"
          echo "✅ Integration tests: PASSED"
          echo "✅ Coverage threshold: PASSED"
          echo ""
          echo "🚀 PR is ready for review and merge!" 